//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testing
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRating
    {
        public int id { get; set; }
        public int userId { get; set; }
        public int testId { get; set; }
        public string rating { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
    }
}
